import fs from 'node:fs'
import path from 'node:path'

// The Vite entry is app.html (source). After the build this turns the compiled
// output into two runnable artifacts:
//
//   index.html            — the entire app inlined into ONE committed file, so
//                           opening the project (double-click, download, or a
//                           static host pointed at the repo) just works.
//   dist/index.html       — the normal multi-file build for hosting, renamed
//                           from app.html so servers find it by default.
//   dist/standalone.html  — the single-file build, alongside dist/ for upload.
//
// Why inline at all: browsers refuse to FETCH ES modules over file://, so a
// multi-file build shows a blank page when opened from disk. Inline scripts
// are not fetched, so a single-file build runs anywhere.
export function standaloneHtml() {
  return {
    name: 'present-value-standalone-html',
    apply: 'build',
    closeBundle() {
      const dist = path.resolve('dist')
      const built = path.join(dist, 'app.html')
      if (!fs.existsSync(built)) return
      const shell = fs.readFileSync(built, 'utf8')

      // Hosted build: same asset references, conventional filename.
      fs.writeFileSync(path.join(dist, 'index.html'), shell)
      fs.rmSync(built)

      let inlined = shell.replace(
        /[ \t]*<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*>\s*/g,
        (whole, href) => {
          const file = path.join(dist, href.replace(/^\.?\//, ''))
          if (!fs.existsSync(file)) return whole
          return `<style>\n${fs.readFileSync(file, 'utf8')}\n</style>\n`
        }
      )
      // Escaping "</script" stops a string literal inside the bundle from
      // terminating the tag early.
      inlined = inlined.replace(
        /[ \t]*<script[^>]*type="module"[^>]*src="([^"]+)"[^>]*><\/script>\s*/g,
        (whole, src) => {
          const file = path.join(dist, src.replace(/^\.?\//, ''))
          if (!fs.existsSync(file)) return whole
          const js = fs.readFileSync(file, 'utf8').replace(/<\/script/gi, '<\\/script')
          return `<script type="module">\n${js}\n</script>\n`
        }
      )

      const banner = '<!-- GENERATED by `npm run build` from app.html — do not edit by hand. ' +
        'This is the whole app in one file so it runs from disk or any host. -->\n'
      fs.writeFileSync(path.resolve('index.html'), banner + inlined)
      fs.writeFileSync(path.join(dist, 'standalone.html'), banner + inlined)
      const kb = (Buffer.byteLength(inlined) / 1024).toFixed(0)
      this.info?.(`index.html + dist/standalone.html ${kb} kB — single file, runs from disk`)
    },
  }
}
