import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

// The Vite entry is app.html (source). After the build this turns the compiled
// output into two runnable artifacts:
//
//   index.html            — the entire app inlined into ONE committed file, so
//                           opening the project (double-click, download, or a
//                           static host pointed at the repo) just works.
//   dist/index.html       — the normal multi-file build for hosting, renamed
//                           from app.html so servers find it by default.
//   dist/standalone.html  — the single-file build, alongside dist/ for upload.
//
// Why inline at all: browsers refuse to FETCH ES modules over file://, so a
// multi-file build shows a blank page when opened from disk. Inline scripts
// are not fetched, so a single-file build runs anywhere.
//
// writeRootIndex: false (an accounts-mode build, see scripts/build-mode.js)
// writes dist/ only and leaves the committed index.html untouched, so the
// committed file is always the local-mode app and CI can check it for drift.
const BANNER = '<!-- GENERATED by `npm run build` from app.html — do not edit by hand. ' +
  'This is the whole app in one file so it runs from disk or any host. -->\n'

// ---------------------------------------------------------------------------
// L18: Content-Security-Policy, as a <meta> tag in each built page.
//
// Only the app's own code runs: inline <script> and <style> blocks are allowed
// by their SHA-256 hash, files by 'self' (multi-file build only), and the
// Supabase project only in an accounts build. Fonts are self-hosted
// (src/styles/fonts.css): the hosted multi-file page loads them from its own
// origin (font-src 'self'); the single file embeds none (size) and uses the
// system fonts (font-src 'none'). No third-party origin is allowed. A <meta>
// CSP cannot carry frame-ancestors or report-uri; set those as HTTP headers if
// the host allows it. `npm run dev` has no CSP (Vite injects its own inline
// scripts there).

export function sha256Source(text) {
  return `'sha256-${crypto.createHash('sha256').update(text, 'utf8').digest('base64')}'`
}

export function contentSecurityPolicy({ self = true, scriptHashes = [], styleHashes = [], fonts = false, connect = [] } = {}) {
  const own = self ? ["'self'"] : []
  const list = items => (items.length ? items.join(' ') : "'none'")
  return [
    "default-src 'self'",
    `script-src ${list([...own, ...scriptHashes])}`,
    `style-src ${list([...own, ...styleHashes])}`,
    `font-src ${list(fonts && self ? ["'self'"] : [])}`,
    "img-src 'self' data:",
    `connect-src ${list(["'self'", ...connect])}`,
    "object-src 'none'",
    "base-uri 'none'",
    "form-action 'none'",
  ].join('; ')
}

function withCsp(html, csp) {
  return html.replace(/(<meta charset="utf-8">\s*)/i, `$1<meta http-equiv="Content-Security-Policy" content="${csp}">\n`)
}

// Inline blocks already in the shell (before anything is inlined into it).
function shellInlineHashes(shell) {
  const styles = [...shell.matchAll(/<style>([\s\S]*?)<\/style>/g)].map(m => sha256Source(m[1]))
  const scripts = [...shell.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)].map(m => sha256Source(m[1]))
  return { styles, scripts }
}

const FONT_FACE = /@font-face\s*\{[^}]*\}/g
const stylesheetHrefs = shell => [...shell.matchAll(/<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*>/g)].map(m => m[1])

// The hosted multi-file page: files from 'self', plus the shell's inline
// blocks; its own font files when its stylesheets declare @font-face.
// readAsset(relativePath) returns a built file's text, or null.
export function multiFileHtml(shell, { connect = [], readAsset = () => null } = {}) {
  const own = shellInlineHashes(shell)
  const fonts = stylesheetHrefs(shell).some(href => (readAsset(href) || '').includes('@font-face'))
  return withCsp(shell, contentSecurityPolicy({
    self: true, scriptHashes: own.scripts, styleHashes: own.styles, fonts, connect,
  }))
}

// The single-file page from the built shell. readAsset(relativePath) returns
// a built file's text, or null when it is not part of the build.
export function singleFileHtml(shell, readAsset, { connect = [] } = {}) {
  const own = shellInlineHashes(shell)
  const styleHashes = [...own.styles]
  const scriptHashes = [...own.scripts]
  let inlined = shell.replace(
    /[ \t]*<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*>\s*/g,
    (whole, href) => {
      const css = readAsset(href)
      if (css == null) return whole
      // No web fonts in the single file: the font files are not embedded
      // (size), so their @font-face rules go too and the system fonts show.
      const body = `\n${css.replace(FONT_FACE, '')}\n`
      styleHashes.push(sha256Source(body))
      return `<style>${body}</style>\n`
    }
  )
  // Escaping "</script" stops a string literal inside the bundle from
  // terminating the tag early.
  // M23: the inlined app moves to the end of <body>. A module script runs
  // only after the page is parsed anyway, and this way the browser can show
  // the "Loading JEZ Tax Suite…" text in #root while the rest of the file is
  // still downloading.
  const scripts = []
  inlined = inlined.replace(
    /[ \t]*<script[^>]*type="module"[^>]*src="([^"]+)"[^>]*><\/script>\s*/g,
    (whole, src) => {
      const js = readAsset(src)
      if (js == null) return whole
      const body = `\n${js.replace(/<\/script/gi, '<\\/script')}\n`
      scriptHashes.push(sha256Source(body))
      scripts.push(`<script type="module">${body}</script>\n`)
      return ''
    }
  )
  inlined = inlined.replace('</body>', () => scripts.join('') + '</body>')
  // No 'self': everything the single file runs is inside it.
  const csp = contentSecurityPolicy({ self: false, scriptHashes, styleHashes, fonts: false, connect })
  return BANNER + withCsp(inlined, csp)
}

export function standaloneHtml({ writeRootIndex = true, connect = [] } = {}) {
  return {
    name: 'present-value-standalone-html',
    apply: 'build',
    api: { writeRootIndex, connect },
    closeBundle() {
      const dist = path.resolve('dist')
      const built = path.join(dist, 'app.html')
      if (!fs.existsSync(built)) return
      const shell = fs.readFileSync(built, 'utf8')

      const readAsset = rel => {
        const file = path.join(dist, rel.replace(/^\.?\//, ''))
        return fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null
      }

      // Hosted build: same asset references, conventional filename.
      fs.writeFileSync(path.join(dist, 'index.html'), multiFileHtml(shell, { connect, readAsset }))
      fs.rmSync(built)

      const single = singleFileHtml(shell, readAsset, { connect })
      fs.writeFileSync(path.join(dist, 'standalone.html'), single)
      const kb = (Buffer.byteLength(single) / 1024).toFixed(0)
      if (writeRootIndex) {
        fs.writeFileSync(path.resolve('index.html'), single)
        this.info?.(`index.html + dist/standalone.html ${kb} kB — single file, runs from disk`)
      } else {
        this.info?.(`dist/standalone.html ${kb} kB (accounts build: the committed index.html was left unchanged)`)
      }
    },
  }
}
